
e ../lots/NOTE/Python/python-bug/stdlib-abc-__instancecheck__-bug.txt

[[
@20241107
Python 3.11.9 (main, Jun 10 2024, 00:57:33)
it seems likely that py.abc use 『x.__class__』 instead of 『type(x)』
===
File "/sdcard/0my_files/git_repos/python3_src/seed/recognize/recognizer_LLoo__ver2_/IRecognizerLLoo.py", line 1374, in <lambda>
    rgnrs = filter(lambda x:isinstance(x, IRecognizerLLoo), locals.values())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 119, in __instancecheck__
  File "/sdcard/0my_files/git_repos/python3_src/seed/types/Namespace.py", line 392, in __getattribute__
    raise AttributeError(name)
AttributeError: __class__
]]

